name: MythicTokens
version: 1.0
main: com.mythictokens.MythicTokensPlugin
api-version: 1.20
authors: [Bhavesh]
description: A premium plugin for mob token abilities in Minecraft.
depend: []
commands:
  token:
    description: Manage MythicTokens
    usage: /<command> [give|remove|toggle] <player|token> [token]
    permission: mythictokens.use
permissions:
  mythictokens.use:
    description: Allows use of the /token command
    default: true
  mythictokens.admin:
    description: Allows admin actions like giving/removing tokens
    default: op